branch-defaults:
  default:
    environment: pcshop-final
  main:
    environment: pcshop-final
environment-defaults:
  pcshop-final:
    branch: null
    repository: null
global:
  application_name: pcshop
  default_ec2_keyname: null
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
